### PR TITLE
Create data model

### PR DESCRIPTION
**Pull request by bimbolabuari**
This PR is about a Microverse project that references an ERD diagram, builds a project schema, creates and runs necessary migration files, includes foreign keys with the corresponding index.

### CODE REVIEW

**Review by oxenprogrammer — CHANGES_REQUESTED** [review]
Hi @bimbolabuari, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>


## Required Changes ♻️
- [ ] Rspec is currently not running the tests. I suggest you update your `rails version` to 6 since I cannot seem to reproduce your solution on any other local machine. Below is the error I get when I try to run the test. 

bimbo

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by bimbolabuari** [comment]
@oxenprogrammer , the test is running on my machine
Probably because we aren't using the same rails or ruby version.

Won't updating my rails version affect all my installation? 🤔

**Comment by oxenprogrammer** [comment]
@bimbolabuari I understand the fact that it is hard to update, but it is for the good of your project. 
You want your project to work across any device and if updating is the solution, then you should go ahead.
Software become obsolete and we will always be required to upgrade.

**Comment by bimbolabuari** [comment]
@oxenprogrammer , I will definitely look into updating my version
I am currently using ruby 2.7 and rails version 5.
I hope the next reviewer will be able to run my application.
Thanks @oxenprogrammer 👍

**Review by emmanuellekamwa — APPROVED** [review]
**STATUS: APPROVED ✔🎉**
Hello @bimbolabuari 👋🏽
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
